# Generated by Django 4.2 on 2023-08-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertaiment',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainments.category'),
        ),
        migrations.AlterField(
            model_name='entertaiment',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
